In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/raw/fredgraph.csv")

FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/fredgraph.csv'

In [3]:
import os
os.getcwd()

'c:\\Users\\ENZO\\Documents\\GitHub\\Commodity-Arbitrage-Analysis\\notebooks'

In [4]:
os.listdir()

['commodity_analysis.ipynb']

In [5]:
import os

os.path.exists("../data/raw/fredgraph.csv")

False

In [6]:
df = pd.read_csv("../data/raw/DCOILBRENTEU.csv")

In [7]:
df.head()

  observation_date  DCOILBRENTEU
0       1987-05-20         18.63
1       1987-05-21         18.45
2       1987-05-22         18.55
3       1987-05-25         18.60
4       1987-05-26         18.63

In [8]:
df.tail()

      observation_date  DCOILBRENTEU
10224       2026-07-28         85.51
10225       2026-07-29         91.95
10226       2026-07-30         91.91
10227       2026-07-31         96.95
10228       2026-08-03         88.90

In [9]:
df.tail(15)

      observation_date  DCOILBRENTEU
10214       2026-07-14         83.69
10215       2026-07-15         83.08
10216       2026-07-16         81.23
10217       2026-07-17         85.01
10218       2026-07-20         86.99
10219       2026-07-21         93.85
10220       2026-07-22         94.12
10221       2026-07-23        105.32
10222       2026-07-24        100.31
10223       2026-07-27         91.82
10224       2026-07-28         85.51
10225       2026-07-29         91.95
10226       2026-07-30         91.91
10227       2026-07-31         96.95
10228       2026-08-03         88.90

In [11]:
df["observation_date"].min(), df["observation_date"].max()

('1987-05-20', '2026-08-03')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10229 entries, 0 to 10228
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  10229 non-null  object
 1   DCOILBRENTEU      9947 non-null   float64
dtypes: float64(1), object(1)
memory usage: 160.0+ KB

In [13]:
df.isna().sum()

observation_date      0
DCOILBRENTEU        282
dtype: int64

In [14]:
df["observation_date"] = pd.to_datetime(df["observation_date"])

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10229 entries, 0 to 10228
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  10229 non-null  datetime64[ns]
 1   DCOILBRENTEU      9947 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 160.0 KB

In [44]:
df = df.rename(columns={"DCOILBRENTEU": "brent_price"})

In [17]:
df.columns

Index(['observation_date', 'brent_price'], dtype='object')

In [18]:
df["brent_price"].describe()

count    9947.000000
mean       51.357571
std        32.775126
min         9.100000
25%        19.600000
50%        46.510000
75%        74.945000
max       143.950000
Name: brent_price, dtype: float64

In [19]:
df.tail(15)

      observation_date  brent_price
10214       2026-07-14        83.69
10215       2026-07-15        83.08
10216       2026-07-16        81.23
10217       2026-07-17        85.01
10218       2026-07-20        86.99
10219       2026-07-21        93.85
10220       2026-07-22        94.12
10221       2026-07-23       105.32
10222       2026-07-24       100.31
10223       2026-07-27        91.82
10224       2026-07-28        85.51
10225       2026-07-29        91.95
10226       2026-07-30        91.91
10227       2026-07-31        96.95
10228       2026-08-03        88.90

In [20]:
df["observation_date"].duplicated().sum()

np.int64(0)

In [21]:
df["brent_price"].min(), df["brent_price"].max()

(np.float64(9.1), np.float64(143.95))

In [22]:
df["brent_price"].isna().sum()

np.int64(282)

In [23]:
wti = pd.read_csv("../data/raw/DCOILWTICO.csv")
gas = pd.read_csv("../data/raw/MHHNGSP.csv")

In [24]:
wti.head()

  observation_date  DCOILWTICO
0       1986-01-02       25.56
1       1986-01-03       26.00
2       1986-01-06       26.53
3       1986-01-07       25.85
4       1986-01-08       25.87

In [25]:
gas.head()

  observation_date  MHHNGSP
0       1997-01-01     3.45
1       1997-02-01     2.15
2       1997-03-01     1.89
3       1997-04-01     2.03
4       1997-05-01     2.25

In [26]:
wti.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10588 entries, 0 to 10587
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  10588 non-null  object
 1   DCOILWTICO        10215 non-null  float64
dtypes: float64(1), object(1)
memory usage: 165.6+ KB

In [27]:
gas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 355 entries, 0 to 354
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  355 non-null    object
 1   MHHNGSP           355 non-null    float64
dtypes: float64(1), object(1)
memory usage: 5.7+ KB

In [29]:
gas = pd.read_csv("../data/raw/DHHNGSP.csv")

In [30]:
gas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7715 entries, 0 to 7714
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  7715 non-null   object
 1   DHHNGSP           7425 non-null   float64
dtypes: float64(1), object(1)
memory usage: 120.7+ KB

In [31]:
brent = pd.read_csv("../data/raw/DCOILBRENTEU.csv")

In [32]:
print("BRENT :", df.columns.tolist())
print("WTI   :", wti.columns.tolist())
print("GAS   :", gas.columns.tolist())

BRENT : ['observation_date', 'brent_price']
WTI   : ['observation_date', 'DCOILWTICO']
GAS   : ['observation_date', 'DHHNGSP']

In [34]:
print("BRENT")
df.info()

print("\nWTI")
wti.info()

print("\nGAS")
gas.info()

BRENT
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10229 entries, 0 to 10228
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  10229 non-null  datetime64[ns]
 1   brent_price       9947 non-null   float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 160.0 KB

WTI
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10588 entries, 0 to 10587
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  10588 non-null  object
 1   DCOILWTICO        10215 non-null  float64
dtypes: float64(1), object(1)
memory usage: 165.6+ KB

GAS
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7715 entries, 0 to 7714
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   observation_date  7715 non-null   object
 1   DHHNGSP           7425 non-null   float64
dtypes: float64(1), object(1)
memory usage: 120.7+ KB

In [36]:
df.head()
wti.head()
gas.head()

  observation_date  DHHNGSP
0       1997-01-07     3.82
1       1997-01-08     3.80
2       1997-01-09     3.61
3       1997-01-10     3.92
4       1997-01-13     4.00

In [37]:
wti["observation_date"] = pd.to_datetime(wti["observation_date"])
gas["observation_date"] = pd.to_datetime(gas["observation_date"])

In [38]:
wti = wti.rename(columns={"DCOILWTICO": "wti_price"})

In [39]:
gas = gas.rename(columns={"DHHNGSP": "natural_gas_price"})

In [47]:
print(df.columns)
print(wti.columns)
print(gas.columns)

Index(['observation_date', 'brent_price'], dtype='object')
Index(['observation_date', 'wti_price'], dtype='object')
Index(['observation_date', 'natural_gas_price'], dtype='object')

In [45]:
df.columns

Index(['observation_date', 'brent_price'], dtype='object')

In [48]:
brent = df.copy()

In [49]:
print("Brent :", brent["observation_date"].min(), "→", brent["observation_date"].max())
print("WTI   :", wti["observation_date"].min(), "→", wti["observation_date"].max())
print("Gas   :", gas["observation_date"].min(), "→", gas["observation_date"].max())

Brent : 1987-05-20 00:00:00 → 2026-08-03 00:00:00
WTI   : 1986-01-02 00:00:00 → 2026-08-03 00:00:00
Gas   : 1997-01-07 00:00:00 → 2026-08-03 00:00:00

In [50]:
print("Brent :", brent["brent_price"].isna().sum())
print("WTI   :", wti["wti_price"].isna().sum())
print("Gas   :", gas["natural_gas_price"].isna().sum())

Brent : 282
WTI   : 373
Gas   : 290

In [51]:
print("Brent :", brent["observation_date"].duplicated().sum())
print("WTI   :", wti["observation_date"].duplicated().sum())
print("Gas   :", gas["observation_date"].duplicated().sum())

Brent : 0
WTI   : 0
Gas   : 0

In [52]:
brent_clean = brent.copy()
wti_clean = wti.copy()
gas_clean = gas.copy()

In [53]:
brent_clean = brent_clean.dropna(subset=["brent_price"])

In [54]:
wti_clean = wti_clean.dropna(subset=["wti_price"])

In [55]:
gas_clean = gas_clean.dropna(subset=["natural_gas_price"])

In [56]:
print("Brent :", brent_clean.shape)
print("WTI   :", wti_clean.shape)
print("Gas   :", gas_clean.shape)

Brent : (9947, 2)
WTI   : (10215, 2)
Gas   : (7425, 2)

In [57]:
brent_clean = brent_clean[
    brent_clean["observation_date"] >= "2025-01-01"
]

wti_clean = wti_clean[
    wti_clean["observation_date"] >= "2025-01-01"
]

gas_clean = gas_clean[
    gas_clean["observation_date"] >= "2025-01-01"
]

In [58]:
print("Brent :", brent_clean.shape)
print("WTI   :", wti_clean.shape)
print("Gas   :", gas_clean.shape)

Brent : (401, 2)
WTI   : (394, 2)
Gas   : (393, 2)

In [59]:
print("Brent :", brent_clean["observation_date"].min(), "→", brent_clean["observation_date"].max())
print("WTI   :", wti_clean["observation_date"].min(), "→", wti_clean["observation_date"].max())
print("Gas   :", gas_clean["observation_date"].min(), "→", gas_clean["observation_date"].max())

Brent : 2025-01-02 00:00:00 → 2026-08-03 00:00:00
WTI   : 2025-01-02 00:00:00 → 2026-08-03 00:00:00
Gas   : 2025-01-02 00:00:00 → 2026-08-03 00:00:00

In [60]:
brent_clean.to_csv(
    "../data/processed/brent_daily_clean.csv",
    index=False
)

wti_clean.to_csv(
    "../data/processed/wti_daily_clean.csv",
    index=False
)

gas_clean.to_csv(
    "../data/processed/natural_gas_daily_clean.csv",
    index=False
)

In [61]:
print(brent_clean.isna().sum())
print(wti_clean.isna().sum())
print(gas_clean.isna().sum())

observation_date    0
brent_price         0
dtype: int64
observation_date    0
wti_price           0
dtype: int64
observation_date     0
natural_gas_price    0
dtype: int64